### ISSUE TITLE
Feature request: Ability to highlight non used fields in Example section and suggest to remove them

### ISSUE THREAD

**Issue by DeepKandey** [karatelabs/intellij-plugin#25]
For e.g.
   Given url URL
   When method GET
    Then status <statusCode>

    Examples:
      | tcSummary                           | statusCode | responseCode |
      | Special Characters Address | 200              | ABC                  |
      
    responseCode variable is not greyed out to highlight that this is not being used and better be deleted, unlike what we used to have in the Cucumber For Java plugin.

**Comment by ptrthomas** [comment]
closing this as `wontfix` since it has not been an issue in the re-worked plugin in 2024
