### ISSUE TITLE
Feature Request: Option to add commas at the end of lists

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/intellij-plugin#49]
Since the JSON parser is very forgiving, it would be great if there was a setting that would format this:
```json
{
  schedule:
  [
    {
      beginYear: 1,
      endYear: 1,
      commissionRate: 50,
      annualizationRate: 100
    }
  ]
}
```
into this:
```json
{
  schedule:
  [
    {
      beginYear: 1,
      endYear: 1,
      commissionRate: 50,
      annualizationRate: 100, // <--- new comma here
    }, // <--- new comma here
  ]
}
```

Simply put, add a comma after the last element of an array or after the last attribute of an object.
This allows for easy adding of additional elements.

**Comment by ptrthomas** [comment]
wow this is an interesting ask. my first reaction is to not support this - or certainly via a setting.

instead - could there be other options. for example, the latest version upploaded to EAP has a feature to "reformat JSON". you can click within any JSON on the RHS or within a doc-string (triple-quote section) and click on the "bulb" icon - https://github.com/karatelabs/karate-intellij-plugin#json-re-formatting

would some similar menu give you what you need ?

**Comment by ptrthomas** [comment]
IntelliJ also can handle "enter key" events. one already is in place when you type a beginning triple-quote and hit ENTER - it automatically adds the ending triple-quote and places your cursor in the right place. would something like that be enough then

**Comment by arnaldop** [comment]
@ptrthomas, to your comment on the reformatting options, while on the one hand I love the flexibility, on the other hand I feel like this does not follow IntelliJ conventions. Specifically, I want to configure in 1 place how all of my JSON snippets look. Perhaps this is for all JSON across my project, or perhaps it is for JSON only in feature files (presumably handled by this plugin).

But it feels like a lot of work to configure each one.
In addition, what happens when I reformat the entire file? Does the plugin remember how each block should be formatted? Or will it format all blocks following a single convention, thus "erasing" individual blocks' selected format?

**Comment by ptrthomas** [comment]
@arnaldop great points. I agree the option to do "lenient" formatting vs "strict" should be a project setting and a single-convention across all files. then we just need a "toggle" option in the UI - which is good

the single vs multi-line is still useful.

do let me know what would be your ideal solution for the trailing comma. if you hit enter after an ending curly-brace would that work ? what is your workflow. do you cut and paste JSON ? we could also auto-add the comma when we detect an opening curly-brace

**Comment by arnaldop** [comment]
@ptrthomas, I'm not sure if I can say what is ideal. Here are some thoughts:
- Reformatting the code (entire file or just snippet) adds the missing trailing commas.
- I like the idea of the opening-brace triggering a previous comma, but how does that behave with a copy/paste instead of typing the opening brace?
- I really do like the idea of converting the lines, primarily because of Karate's lightweight JSON style. This means when I copy JSON from another source, like `curl` or Chrome output, it would be great to have the plugin convert that to Karate JSON, and vice versa.
   - I don't know if this gets more obscure, but IntelliJ already has a Copy/Paste Special dialog (image below), and perhaps this could be the place for these conversions. Note that keyboard shortcuts are supported within this menu, which would allow us to use these Karate Plugin conversion features without clicking (which is a big deal for me!)

Interestingly, IntelliJ does this quite nicely in my karate-config.js:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/e4c9734e-777a-43f8-9420-dc9b2cb18b5c)

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/b3792fc6-7c56-4c04-9219-c2ae4478f0d1)

**Comment by chr-istopher** [comment]
I thought the JSON standard was not to have a trailing comma after the last element in an array? Won't this break features that contain correctly-formatted JSON requests?

<img width="1135" alt="Screenshot 2024-03-22 at 15 43 12" src="https://github.com/karatelabs/intellij-plugin/assets/8940420/6c877bc0-a915-4878-a213-8995e9443373">

**Comment by arnaldop** [comment]
@chr-istopher, I understand what you are saying.
However, Karate Core is more flexible than that, and has no problems with trailing commas.
I am only advocating that this plugin behave or allow as much as the Karate core allows.

In addition, some IDEs (IntelliJ, for example) will flag it on one side, but correct it on paste.
IntelliJ will take this `[ {}, ]` and paste it as this:
```
[
  {}
]
```.
So if IDEs can handle it, and Karate Core can also, then the Plugin should be able to handle it too.

**Comment by ptrthomas** [comment]
after thinking about this for a bit - will close as `wontfix`
