### ISSUE TITLE
Endless Formatting Bug

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/intellij-plugin#53]
(Version: 2.0.0.25)
Reformatting a file repeatedly leads to the following behavior. Watch the strings continually move to the right.

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/a612b71b-e0b9-47e5-9f82-27bb43c3106e)

![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/b5a71b3a-4736-45f4-8a6d-4f752f02776e)

After a few more:
![image](https://github.com/karatelabs/karate-intellij-plugin/assets/6642062/10095a0a-4534-42cb-bddc-4508dacccceb)

**Comment by ptrthomas** [comment]
@arnaldop sure will fix.

btw `set` is not needed if you are doing a pure-js-object mutation on one-line
`* foo.bar = 'baz'` will work fine

**Comment by ptrthomas** [comment]
@arnaldop just to make sure I understand you mean the equals sign be surrounded by one space ? yes

**Comment by arnaldop** [comment]
Yes, surrounded by 1 space. In other words, revert this sliding to the right format.

**Comment by arnaldop** [comment]
Don't know if this should be added here or to a different ticket.

Now, this:
```
    * text payload =
      """
      ...
      """
```

keeps turning into this:
```
    * text payload =

      """
      ...
      """
```

Note the newly added blank link after the `text` line.

**Comment by ptrthomas** [comment]
should be fixed in latest EAP: https://github.com/karatelabs/intellij-plugin/releases/tag/v2.0.0.EAP
