### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/intellij-plugin#59]
Lines that Karate handles fine but that the plugin does not like.

![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/fa6dd9e9-a9e5-4580-8ac8-78523da17bd1)

![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/6ffcf158-698f-408c-b8c8-89625bed682a)

![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/579fe549-e835-4716-9ea8-b37430d01ce5)

**Comment by ptrthomas** [comment]
@arnaldop can you re-check, I'm pretty sure these are fixed in the latest EA version (not yet on the marketplace): 2.0.2.34 https://github.com/karatelabs/intellij-plugin/releases/tag/v2.0.0.EAP

**Comment by arnaldop** [comment]
@ptrthomas, with 2.0.2.34, I am getting these:
![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/b82d1dd0-996e-483c-978f-5d4dbbab7dfa)
![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/bbecbc5f-f090-494b-900f-f06c2cf0028a)

**Comment by ptrthomas** [comment]
fixed in 2.0.2 available at the marketplace:

**Comment by arnaldop** [comment]
@ptrthomas, still has 1 issue from the original ones above.
![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/7e3174ce-6637-4956-9432-0b82203590e6)

**Comment by ptrthomas** [comment]
@arnaldop sorry I'm unable to replicate this and I don't understand why one line is greyed out. it would really help if you can post a snippet of code, feel free to open a new issue
