### ISSUE TITLE
'match header' formatting breaks

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/intellij-plugin#60]
Karate docs (https://karatelabs.github.io/karate/#match-header):
```
# so after a http request
Then match header Content-Type == 'application/json'
# 'contains' works as well
Then match header Content-Type contains 'application'
```

After formatting:
```
  # so after a http request
    Then match header Content - Type == 'application/json'
  # 'contains' works as well
    Then match header Content - Type contains 'application'
```

The comment being moved back 1 indent level is a bit annoying, but the fact that header names are broken definitely conflicts with Karate Core.

**Comment by ptrthomas** [comment]
@arnaldop fixed in 2.0.3 available on the marketplace
