### ISSUE TITLE
Karate.env overwrite Tags propterty

### ISSUE THREAD

**Issue by ThierryLejeune** [karatelabs/intellij-plugin#61]
Hello
I use the intellij karate plugin and when I edit karate feature configuration "karate.env* property to run the test, no test is found !
because the scenarios are filted by Tag with the value of the karate.env property.

Class: KarateRunProfileState
Method: protected JavaParameters createJavaParameters() throws ExecutionException 
line --> 
        String karateTags = config.getKarateEnv();
        if (karateTags != null) {
            params.getProgramParametersList().add("-t", karateTags);
        }

Best regards
Thierry

**Comment by ptrthomas** [comment]
@ThierryLejeune thanks for this report - we will fix this ASAP

**Comment by ptrthomas** [comment]
@ThierryLejeune this is fixed in 2.0.3 now available on the marketplace
