### ISSUE TITLE
Environment variables field missing with latest plugin

### ISSUE THREAD

**Issue by nicwaters823** [karatelabs/intellij-plugin#63]
Hi,

I upgraded couple of day ago to the latest version of the Karate plugin, and unfortunately all my local config broke, for a project I have where we override environment variables.

Previously I'd do this by just adding the env vars to the run config - but the field isn't there anymore.

As a workaround I can use a karate env e.g. 'local' and then copy my entire karate.config.js, but I'd rather not do this long term, because our karate.config.js is quite large, and it'll be an overhead for maintainers to have to all update their local ones, every time someone changes karate.config.js 

would it be possible to restore the env vars field?

thanks

**Comment by nicwaters823** [comment]
<img width="463" alt="IDEA_run_config" src="https://github.com/karatelabs/intellij-plugin/assets/143523074/6d11f102-29e6-4211-a807-3c9e35d78546">
here's a screenshot from the old run config (sorry it's only a tiny fragment but I can't sanitise a larger one because Intellij marked the old ones as invalid and hid them:) and all I have is one image from my team's documentation

**Comment by nicwaters823** [comment]
thanks for the prompt response:)

**Comment by ptrthomas** [comment]
@nicwaters823 this has been fixed in the latest version 2.0.5 available at the marketplace: https://plugins.jetbrains.com/plugin/19232-karate
