### ISSUE TITLE
Code reformatting does not reformat Examples and  JSON request data tables

### ISSUE THREAD

**Issue by chr-istopher** [karatelabs/intellij-plugin#64]
Tables such as:

Examples:
| a | b |
| c | d |

used to aligned with the IntelliJ Code... Reformat Code option but this has recently stopped working. Plugin version 2.0.5

IntelliJ IDEA 2023.3.6 (Community Edition)
Build #IC-233.15026.9, built on March 21, 2024
Runtime version: 17.0.10+1-b1087.23 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  io.karatelabs.intellij (2.0.5)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
Kotlin: 233.15026.9-IJ

**Comment by ptrthomas** [comment]
@chr-istopher this is fixed in 2.0.6 now available on the jetbrains marketplace. thanks and please keep the feedback coming !
