### ISSUE TITLE
Cannot set breakpoints for features in jars

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/intellij-plugin#65]
Issues
1. cannot step into call read('classpath:…​) for features provided by jars
2. breakpoints from features provided by jars are ignored/skipped

mvc: https://github.com/ericdriggs/karate-plugin-jar-classpath

**Comment by ptrthomas** [comment]
acknowledged, will take a look

**Comment by ptrthomas** [comment]
fixed in 2.0.7
