### ISSUE TITLE
Formatting is inconsistent

### ISSUE THREAD

**Issue by arnaldop** [karatelabs/intellij-plugin#66]
- ![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/171aa6ee-966d-426b-9cfd-e2725e4693cf)
  - extraneous spaces
- ![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/70498230-7a45-4e9a-a40c-889fdc9e73ea)
  - extraneous spaces
  - multiple properties kept in the same line
- ![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/507b3306-2286-4b9a-ad94-fcef329b9ee3)
  - missing spaces after colon
- ![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/9dabcb11-2be7-4b8f-9a19-046081483c5d) to ![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/d786a7ba-b966-41ec-986c-a52092aaaaed)
  - moving lines does not adjust commas, which causes missing comma warning
- ![image](https://github.com/karatelabs/intellij-plugin/assets/6642062/d8149da3-6fec-4afa-98b8-5a3ed0d0074c)
  - no standard handling of single/double quotes

**Comment by ptrthomas** [comment]
acknowledged, will take a look

**Comment by ptrthomas** [comment]
@arnaldop to be clear the option to convert JSON is available only in the PRO subscription. I haven't investigated this yet - but I feel some of the issues (e.g. the last one in first comment) are solved with that feature

**Comment by ptrthomas** [comment]
first issue is fixed in 2.0.7 available now. for JSON formatting - the PRO version is needed
