### ISSUE TITLE
Failed to Perform Operation Cannot perform operation. Too complex, sorry.

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/intellij-plugin#67]
When debugging complex features, receive error "Failed to Perform Operation Cannot perform operation. Too complex, sorry."
After this point, as temporary workaround can close and relaunch Intellij. Run->Debug will produce "Error running. Java heap space". Context menu debug option is slow to load and will error with "Failed to perform operation..."

Using heap size 3072MB

![failed-to-perform-operation](https://github.com/karatelabs/intellij-plugin/assets/1097979/03dfd04d-c56f-43c3-8ccc-ef8716c78942)

**Comment by ericdriggs** [comment]
![error-running-java-heap-space](https://github.com/karatelabs/intellij-plugin/assets/1097979/961c68d3-c40f-45ec-88e6-d2c95ffb5dcd)

**Comment by ericdriggs** [comment]
<img width="492" alt="intellij-heap-3072MB" src="https://github.com/karatelabs/intellij-plugin/assets/1097979/552e2b3f-e3cc-4e2b-a790-5a4bebc8f41f">

**Comment by ptrthomas** [comment]
closing as this was some other issue
