### ISSUE TITLE
json path filter in match expression marked as error

### ISSUE THREAD

**Issue by ericdriggs** [karatelabs/intellij-plugin#70]
`* match cat.kittens[?(@.id==23)].name == ["Bob"]`

`# ? is marked as error: <array element>, <expr> or KarateTokenType.R_BRACKET expected, got '?'`

**Comment by ptrthomas** [comment]
will be fixed in next version shortly

**Comment by ptrthomas** [comment]
fix now available in plugin version 2.1.0
